environments          = "devolopment"
s3BucketName          = "s3usw2appgredpsidevtfstate"
eksClusterName        = "eks-RISE-SANDBOX"
clusterRoleName       = "EKSClusterAuto"
clusterNodeRoleName   = "EKSWorkerNodeRole"
endpointPrivateAccess = "true"
endpointPublicAccess  = "true"
subnetIds = ["subnet-0f1379c2b55c00806","subnet-0a967c13de5449c04","subnet-079f767877cbe68c4"]
tags = {
  environment = "Development"
  source      = "Terraform"
}
nodeGroupName        = "nodegrp1"
nodeDesiredSize      = 1
nodeMaxSize          = 3
nodeMinSize          = 1
vpcId                = "vpc-0ebec54e5b8c253eb"
securityGroupName    = "clusterSecurityGroup"
capacityType         = "SPOT"
autoScalingGroupName = "eks-spot-instance-autoscaling"
amiId                = "ami-0f7de5cb4a0ef5195"
instanceType         = "t3.medium"
instanceKey          = "EKS-RISE-SANDBOX"
launchTemplateName   = "eks-spotinstance"
eksLogTypes          = ["api", "audit", "authenticator", "controllerManager", "scheduler"]